name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - 'v*'
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        # Install a specific version of uv.
        version: "0.6.6"

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Run tests with coverage
      run: |
        uv run pytest --cov=lxd_io --cov-report=xml --cov-report=term-missing test

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml

    - name: Comment coverage on PR
      uses: orgoro/coverage-comment-action@v1
      with:
        coverageFile: coverage.xml

    - name: Lint code with ruff
      run: |
        uv run ruff check --output-format=github .
